theme = "iroaseta"

[editor]
bufferline = "multiple"
color-modes = true
cursorline = true
line-number = "absolute"
lsp.display-inlay-hints = true
mouse = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true

# [editor.lsp]
# display-inlay-hints = true
# display-messages = true

[editor.statusline]
center = ["file-name"]
left = ["mode", "register", "selections", "spinner"]
right = ["diagnostics", "version-control", "file-encoding", "file-line-ending", "total-line-numbers", "file-type"]
mode.insert = "INSERT"
mode.normal = "NORMAL"
mode.select = "SELECT"
separator = "|"

[keys.normal]
C-g = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]
esc = ["collapse_selection", "keep_primary_selection"]
