# theme = "catppuccin_mocha"
theme = "iroaseta"

[editor]
bufferline = "multiple"
color-modes = true
cursorline = true
line-number = "absolute"
lsp.display-inlay-hints = true
mouse = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true

[editor.statusline]
center = ["file-name"]
left = ["mode", "spinner"]
right = ["file-encoding", "file-line-ending", "file-type"]
mode.insert = "INSERT"
mode.normal = "NORMAL"
mode.select = "SELECT"
separator = "|"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
